/**
 * Writes src/data/bibleBooks.js from whatever translations are installed under
 * public/bible/.
 *
 * Shared by both the scripts that install one: scripts/sync-bible.mjs, which
 * turns a local scrape into the Tagalog text, and scripts/fetch-bible.mjs,
 * which downloads a public-domain English one. Either way the table has to end
 * up describing every translation on disk, not just the one that was added —
 * which is why it is built by looking at the directory rather than by the
 * script that happened to run.
 *
 * The table is in the bundle rather than fetched, so that a reference can be
 * typed and accepted or refused with no network at all. Only verses are
 * fetched.
 */
import { readFileSync, writeFileSync, readdirSync, existsSync, statSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const shelf = join(root, 'public', 'bible')

/**
 * The translation a church gets before anybody chooses one.
 *
 * Tagalog, because that is what the congregations this was built for read
 * aloud on a Sunday. A church that wants English is two taps away, and the
 * choice is remembered against the account.
 */
export const DEFAULT_VERSION = 'MBBTAG'

/** Listed first, then the rest alphabetically — the default leads the picker. */
const order = (a, b) => {
  if (a.id === DEFAULT_VERSION) return -1
  if (b.id === DEFAULT_VERSION) return 1
  return a.id.localeCompare(b.id)
}

/** Every version with an index.json, newest scrape or download alike. */
const installed = () =>
  readdirSync(shelf)
    .filter((name) => statSync(join(shelf, name)).isDirectory())
    .filter((name) => existsSync(join(shelf, name, 'index.json')))
    .map((name) => JSON.parse(readFileSync(join(shelf, name, 'index.json'), 'utf-8')))
    .map((index) => ({ ...index, id: index.version }))
    .sort(order)

export const writeBibleTable = () => {
  const versions = installed()
  if (!versions.length) throw new Error('No translations in public/bible/')

  const base = versions.find((v) => v.id === DEFAULT_VERSION) || versions[0]

  // Canonical order comes from one translation and the rest are matched into
  // it by slug. The slug is the filename, and every translation uses the same
  // sixty-six, so a book missing from one simply has no name under its id and
  // falls back to English at the point of display.
  const books = base.books.map((book) => {
    const names = {}
    versions.forEach((version) => {
      const match = version.books.find((b) => b.slug === book.slug)
      if (match) names[version.id] = match.name || match.en || book.slug
    })
    return {
      slug: book.slug,
      en: book.en,
      testament: book.testament,
      chapters: book.chapters,
      names,
    }
  })

  const table = `/**
 * The translations installed and the 66 books they hold, in canonical order —
 * GENERATED by scripts/bible-table.mjs. Do not edit by hand; run
 * scripts/fetch-bible.mjs or scripts/sync-bible.mjs instead.
 *
 * This is in the bundle rather than fetched so that typing a reference, and
 * being told it is wrong, needs no network. Only the verses are fetched.
 *
 * BIBLE_VERSIONS
 *   id         the folder under public/bible/, and what a saved preference
 *              and the chip in the reader's corner both hold
 *   name       what the picker calls it
 *   note       the line under that name, e.g. "Tagalog, 2005 edition"
 *   language   the picker groups by this
 *
 * BIBLE_BOOKS
 *   slug       the filename under public/bible/<version>/
 *   en         the English name, and the fallback wherever a translation has
 *              no name of its own for a book
 *   names      what each installed translation prints, e.g. "Mga Awit" for
 *              Psalms — keyed by version id
 *   chapters   how many, so "Genesis 51" can be refused before anyone stands
 *              up in front of a congregation with it
 */
export const DEFAULT_BIBLE_VERSION = ${JSON.stringify(DEFAULT_VERSION)}

export const BIBLE_VERSIONS = ${JSON.stringify(
    versions.map((v) => ({
      id: v.id,
      name: v.name || v.id,
      short: v.short || v.id,
      note: v.note || '',
      language: v.language || 'English',
      languageCode: v.languageCode || 'en',
      verses: v.verse_count,
    })),
    null,
    2
  )}

export const BIBLE_BOOKS = ${JSON.stringify(books, null, 2)}
`

  writeFileSync(join(root, 'src', 'data', 'bibleBooks.js'), table)

  console.log(
    'Wrote src/data/bibleBooks.js — ' +
      versions.map((v) => `${v.id} (${v.language})`).join(', ')
  )
}

// Runnable on its own, for when a translation folder was added or removed by
// hand and the table needs to catch up.
if (process.argv[1] && process.argv[1].endsWith('bible-table.mjs')) writeBibleTable()
