/**
 * Turns a scrape in data/bible/ into the two things the app actually ships.
 *
 * The scrape is 190 MB, 162 of it the scraper's own HTML request cache,
 * and it is gitignored — publisher-copyrighted text we do not want in git by
 * accident. What the app needs out of it is far smaller:
 *
 *   public/bible/<VERSION>/<Book>.json   one file per book, minified, fetched
 *                                        on demand: 2-89 KB gzipped, 35 KB for
 *                                        a gospel
 *   src/data/bibleBooks.js               the 66-book table, generated by
 *                                        scripts/bible-table.mjs out of every
 *                                        translation on the shelf, so a
 *                                        reference can be typed and validated
 *                                        with no network at all
 *
 * Re-run after scraping a new translation:  node scripts/sync-bible.mjs
 */
import { readFileSync, writeFileSync, mkdirSync, rmSync, existsSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { writeBibleTable } from './bible-table.mjs'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const VERSION = process.argv[2] || 'MBBTAG'

const src = join(root, 'data', 'bible', VERSION)
const out = join(root, 'public', 'bible', VERSION)

if (!existsSync(src)) {
  console.error(`No scrape at data/bible/${VERSION}. Run scripts/scrape_bible.py first.`)
  process.exit(1)
}

const index = JSON.parse(readFileSync(join(src, 'index.json'), 'utf-8'))

// Canonical order comes from the index; the filename is what the client will
// fetch, so the two have to be matched up here rather than guessed at runtime.
const slugOf = (book) => book.replace(/ /g, '-')

if (existsSync(out)) rmSync(out, { recursive: true })
mkdirSync(out, { recursive: true })

let bytes = 0
const books = index.books.map(({ book, testament, chapters, verses }) => {
  const slug = slugOf(book)
  const data = JSON.parse(readFileSync(join(src, 'books', `${slug}.json`), 'utf-8'))

  // Only the verses travel. Dropping the scrape's provenance fields — source
  // URL, timestamp, the counts already in the index — is most of the saving,
  // and minifying is the rest.
  const payload = JSON.stringify({
    version: data.version,
    book: data.book,
    book_localized: data.book_localized,
    chapters: data.chapters.map((c) => ({
      chapter: c.chapter,
      verses: c.verses.map((v) => ({ verse: v.verse, text: v.text })),
    })),
  })
  writeFileSync(join(out, `${slug}.json`), payload)
  bytes += payload.length

  return {
    slug,
    en: book,
    // What this translation prints — "Mga Awit" for Psalms. The table builder
    // reads it under the same key from every translation, English included,
    // where it happens to be the English name.
    name: data.book_localized || book,
    testament,
    chapters,
    verses,
  }
})

/**
 * How a translation names itself in the picker. The scrape carries its code
 * and nothing else, so the readable part lives here.
 *
 * The language is part of it because the picker groups by language, and this
 * script is the one that scrapes — the next translation through it may well
 * not be Tagalog. An unknown code stops here rather than being labelled with
 * the last one's language, which would put an English Bible under a Tagalog
 * heading and give no sign anything was wrong.
 */
const LABELS = {
  MBBTAG: {
    name: 'Magandang Balita Biblia',
    short: 'MBBTAG',
    note: 'Tagalog, 2005 edition',
    language: 'Tagalog',
    languageCode: 'tl',
  },
}

const label = LABELS[VERSION]
if (!label) {
  console.error(
    `No label for ${VERSION}. Add one to LABELS in scripts/sync-bible.mjs — the picker ` +
      `needs a readable name and a language, and the scrape carries neither.`
  )
  process.exit(1)
}

// A per-version manifest, so the app can tell which translations are installed
// without probing for files.
writeFileSync(
  join(out, 'index.json'),
  JSON.stringify({
    version: index.version,
    name: label.name,
    short: label.short,
    note: label.note,
    language: label.language,
    languageCode: label.languageCode,
    book_count: books.length,
    verse_count: index.verse_count,
    books,
  })
)

console.log(
  `${VERSION}: ${books.length} books, ${index.verse_count} verses -> public/bible/${VERSION}/ ` +
    `(${(bytes / 1024 / 1024).toFixed(1)} MB minified)`
)

// Every translation on the shelf, not only this one: the table describes all
// of them, and rebuilding it from the directory is what stops a version added
// by fetch-bible.mjs disappearing the next time this runs.
writeBibleTable()
